import { PlayerAttack } from '@blert/common';

export const enum CombatStyle {
  MELEE,
  RANGED,
  MAGIC,
}

type AttackMetadata = {
  tagColor: string | undefined;
  letter: string;
  ranged: boolean;
  special: boolean;
  style: CombatStyle | null;
};

export const ATTACK_METADATA: { [attack in PlayerAttack]: AttackMetadata } = {
  [PlayerAttack.ABYSSAL_BLUDGEON]: {
    tagColor: 'red',
    letter: 'BLD',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.ACCURSED_SCEPTRE_AUTO]: {
    tagColor: 'yellow',
    letter: 'as',
    ranged: false,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.ACCURSED_SCEPTRE_SPEC]: {
    tagColor: 'yellow',
    letter: 'AS',
    ranged: false,
    special: true,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.AGS_SPEC]: {
    tagColor: 'yellow',
    letter: 'AGS',
    ranged: false,
    special: true,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.ATLATL_AUTO]: {
    tagColor: 'green',
    letter: 'atl',
    ranged: true,
    special: false,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.ATLATL_SPEC]: {
    tagColor: 'green',
    letter: 'ATL',
    ranged: true,
    special: true,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.BGS_SPEC]: {
    tagColor: 'yellow',
    letter: 'BGS',
    ranged: false,
    special: true,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.BLOWPIPE]: {
    tagColor: 'green',
    letter: 'BP',
    ranged: true,
    special: false,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.BLOWPIPE_SPEC]: {
    tagColor: 'green',
    letter: 'BPs',
    ranged: true,
    special: true,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.BOWFA]: {
    tagColor: 'green',
    letter: 'BFa',
    ranged: true,
    special: false,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.BURNING_CLAW_SCRATCH]: {
    tagColor: 'red',
    letter: 'bc',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.BURNING_CLAW_SPEC]: {
    tagColor: 'red',
    letter: 'BC',
    ranged: false,
    special: true,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.CHALLY_SPEC]: {
    tagColor: 'yellow',
    letter: 'CH',
    ranged: false,
    special: true,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.CHALLY_SWIPE]: {
    tagColor: 'yellow',
    letter: 'ch',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.CHIN_BLACK]: {
    tagColor: 'green',
    letter: 'CCB',
    ranged: true,
    special: false,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.CHIN_GREY]: {
    tagColor: 'green',
    letter: 'CCG',
    ranged: true,
    special: false,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.CHIN_RED]: {
    tagColor: 'green',
    letter: 'CCR',
    ranged: true,
    special: false,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.CLAW_SCRATCH]: {
    tagColor: 'red',
    letter: 'c',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.CLAW_SPEC]: {
    tagColor: 'red',
    letter: 'C',
    ranged: false,
    special: true,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.DAWN_AUTO]: {
    tagColor: 'yellow',
    letter: 'db',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.DAWN_SPEC]: {
    tagColor: 'yellow',
    letter: 'DB',
    ranged: true,
    special: true,
    style: null,
  },
  [PlayerAttack.DART]: {
    tagColor: 'green',
    letter: 'D',
    ranged: true,
    special: false,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.DDS_POKE]: {
    tagColor: 'yellow',
    letter: 'dds',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.DDS_SPEC]: {
    tagColor: 'yellow',
    letter: 'DDS',
    ranged: false,
    special: true,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.DHAROKS_GREATAXE]: {
    tagColor: 'red',
    letter: 'DH',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.DINHS_SPEC]: {
    tagColor: 'yellow',
    letter: 'BW',
    ranged: false,
    special: true,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.DRAGON_HUNTER_LANCE]: {
    tagColor: 'red',
    letter: 'DHL',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.DRAGON_SCIMITAR]: {
    tagColor: 'red',
    letter: 'DS',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.DUAL_MACUAHUITL]: {
    tagColor: 'red',
    letter: 'DMC',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.ELDER_MAUL]: {
    tagColor: 'red',
    letter: 'eld',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.ELDER_MAUL_SPEC]: {
    tagColor: 'red',
    letter: 'ELD',
    ranged: false,
    special: true,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.FANG_STAB]: {
    tagColor: 'red',
    letter: 'FNG',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.GOBLIN_PAINT_CANNON]: {
    tagColor: 'red',
    letter: 'GPC',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.GODSWORD_SMACK]: {
    tagColor: 'yellow',
    letter: 'gs',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.GUTHANS_WARSPEAR]: {
    tagColor: 'red',
    letter: 'GW',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.HAM_JOINT]: {
    tagColor: 'red',
    letter: 'HAM',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.HAMMER_BOP]: {
    tagColor: 'red',
    letter: 'h',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.HAMMER_SPEC]: {
    tagColor: 'red',
    letter: 'H',
    ranged: false,
    special: true,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.INQUISITORS_MACE]: {
    tagColor: 'red',
    letter: 'IM',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.KARILS_CROSSBOW]: {
    tagColor: 'green',
    letter: 'KC',
    ranged: true,
    special: false,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.KICK]: {
    tagColor: undefined,
    letter: 'k',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.KODAI_BARRAGE]: {
    tagColor: 'blue',
    letter: 'F',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.KODAI_BASH]: {
    tagColor: 'blue',
    letter: 'kb',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.NM_STAFF_BARRAGE]: {
    tagColor: 'blue',
    letter: 'F',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.NM_STAFF_BASH]: {
    tagColor: 'blue',
    letter: 'vnm',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.NOXIOUS_HALBERD]: {
    tagColor: 'red',
    letter: 'NH',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.PUNCH]: {
    tagColor: undefined,
    letter: 'p',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.RAPIER]: {
    tagColor: 'red',
    letter: 'R',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.SAELDOR]: {
    tagColor: 'red',
    letter: 'B',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.SANG]: {
    tagColor: 'blue',
    letter: 'T',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.SANG_BARRAGE]: {
    tagColor: 'blue',
    letter: 'F',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.SCEPTRE_BARRAGE]: {
    tagColor: 'blue',
    letter: 'F',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.SCYTHE]: {
    tagColor: 'red',
    letter: 'S',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.SCYTHE_UNCHARGED]: {
    tagColor: 'red',
    letter: 's',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.SGS_SPEC]: {
    tagColor: 'yellow',
    letter: 'SGS',
    ranged: false,
    special: true,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.SHADOW]: {
    tagColor: 'blue',
    letter: 'Sh',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.SHADOW_BARRAGE]: {
    tagColor: 'blue',
    letter: 'F',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.SOTD_BARRAGE]: {
    tagColor: 'blue',
    letter: 'F',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.SOULREAPER_AXE]: {
    tagColor: 'red',
    letter: 'AXE',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.STAFF_OF_LIGHT_BARRAGE]: {
    tagColor: 'blue',
    letter: 'F',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.STAFF_OF_LIGHT_SWIPE]: {
    tagColor: 'blue',
    letter: 'SOL',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.SWIFT_BLADE]: {
    tagColor: 'red',
    letter: 'SB',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.TENT_WHIP]: {
    tagColor: 'red',
    letter: 'TW',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.TORAGS_HAMMERS]: {
    tagColor: 'red',
    letter: 'TH',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.TOXIC_TRIDENT]: {
    tagColor: 'blue',
    letter: 'T',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.TOXIC_TRIDENT_BARRAGE]: {
    tagColor: 'blue',
    letter: 'F',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.TOXIC_STAFF_BARRAGE]: {
    tagColor: 'blue',
    letter: 'F',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.TOXIC_STAFF_SWIPE]: {
    tagColor: 'blue',
    letter: 'TS',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.TRIDENT]: {
    tagColor: 'blue',
    letter: 'T',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.TRIDENT_BARRAGE]: {
    tagColor: 'blue',
    letter: 'F',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.TONALZTICS_AUTO]: {
    tagColor: 'yellow',
    letter: 'ga',
    ranged: true,
    special: false,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.TONALZTICS_SPEC]: {
    tagColor: 'yellow',
    letter: 'G',
    ranged: true,
    special: true,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.TONALZTICS_UNCHARGED]: {
    tagColor: 'yellow',
    letter: 'g',
    ranged: true,
    special: true,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.TWISTED_BOW]: {
    tagColor: 'green',
    letter: 'TB',
    ranged: true,
    special: false,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.VENATOR_BOW]: {
    tagColor: 'green',
    letter: 'VB',
    ranged: true,
    special: false,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.VERACS_FLAIL]: {
    tagColor: 'red',
    letter: 'VF',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.VOIDWAKER_AUTO]: {
    tagColor: 'yellow',
    letter: 'vw',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.VOIDWAKER_SPEC]: {
    tagColor: 'yellow',
    letter: 'VW',
    ranged: false,
    special: true,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.VOLATILE_NM_SPEC]: {
    tagColor: 'blue',
    letter: 'VNM',
    ranged: true,
    special: true,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.WEBWEAVER_AUTO]: {
    tagColor: 'green',
    letter: 'ww',
    ranged: true,
    special: false,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.WEBWEAVER_SPEC]: {
    tagColor: 'green',
    letter: 'WW',
    ranged: true,
    special: true,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.XGS_SPEC]: {
    tagColor: 'yellow',
    letter: 'XGS',
    ranged: false,
    special: true,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.ZCB_AUTO]: {
    tagColor: 'green',
    letter: 'zcb',
    ranged: true,
    special: false,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.ZCB_SPEC]: {
    tagColor: 'green',
    letter: 'ZCB',
    ranged: true,
    special: true,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.ZGS_SPEC]: {
    tagColor: 'yellow',
    letter: 'ZGS',
    ranged: false,
    special: true,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.ZOMBIE_AXE]: {
    tagColor: 'red',
    letter: 'ZMB',
    ranged: false,
    special: false,
    style: CombatStyle.MELEE,
  },
  [PlayerAttack.UNKNOWN_BARRAGE]: {
    tagColor: undefined,
    letter: 'F',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.UNKNOWN_BOW]: {
    tagColor: 'green',
    letter: 'UNK',
    ranged: true,
    special: false,
    style: CombatStyle.RANGED,
  },
  [PlayerAttack.UNKNOWN_POWERED_STAFF]: {
    tagColor: 'blue',
    letter: 'UNK',
    ranged: true,
    special: false,
    style: CombatStyle.MAGIC,
  },
  [PlayerAttack.UNKNOWN]: {
    tagColor: undefined,
    letter: 'UNK',
    ranged: false,
    special: false,
    style: null,
  },
};
