export const enum Column {
  UUID,
  DATE,
  TYPE,
  STATUS,
  SCALE,
  PARTY,
  CHALLENGE_TIME,
  OVERALL_TIME,
  TOTAL_DEATHS,

  // Split columns.
  MAIDEN_ROOM,
  MAIDEN_70S,
  MAIDEN_50S,
  MAIDEN_30S,
  BLOAT_ROOM,
  NYLOCAS_ROOM,
  NYLOCAS_BOSS_SPAWN,
  NYLOCAS_BOSS,
  SOTETSEG_ROOM,
  SOTETSEG_66,
  SOTETSEG_33,
  XARPUS_ROOM,
  XARPUS_SCREECH,
  VERZIK_ROOM,
  VERZIK_P1,
  VERZIK_P2,
  VERZIK_P3,
  INFERNO_WAVE_9,
  INFERNO_WAVE_18,
  INFERNO_WAVE_25,
  INFERNO_WAVE_35,
  INFERNO_WAVE_42,
  INFERNO_WAVE_50,
  INFERNO_WAVE_57,
  INFERNO_WAVE_60,
  INFERNO_WAVE_63,
  INFERNO_WAVE_66,
  INFERNO_WAVE_68,
  INFERNO_WAVE_69,
  COLOSSEUM_WAVE_1,
  COLOSSEUM_WAVE_2,
  COLOSSEUM_WAVE_3,
  COLOSSEUM_WAVE_4,
  COLOSSEUM_WAVE_5,
  COLOSSEUM_WAVE_6,
  COLOSSEUM_WAVE_7,
  COLOSSEUM_WAVE_8,
  COLOSSEUM_WAVE_9,
  COLOSSEUM_WAVE_10,
  COLOSSEUM_WAVE_11,
  COLOSSEUM_WAVE_12,
  MOKHAIOTL_DELVE_1,
  MOKHAIOTL_DELVE_2,
  MOKHAIOTL_DELVE_3,
  MOKHAIOTL_DELVE_4,
  MOKHAIOTL_DELVE_5,
  MOKHAIOTL_DELVE_6,
  MOKHAIOTL_DELVE_7,
  MOKHAIOTL_DELVE_8,

  MOKHAIOTL_DELVE,
  MOKHAIOTL_MAX_COMPLETED_DELVE,
}

export type SelectedColumn = {
  column: Column;
};

export type PresetColumns = {
  name: string;
  id: number;
  columns: SelectedColumn[];
};

export const DEFAULT_SELECTED_COLUMNS: SelectedColumn[] = [
  { column: Column.DATE },
  { column: Column.TYPE },
  { column: Column.STATUS },
  { column: Column.SCALE },
  { column: Column.PARTY },
  { column: Column.CHALLENGE_TIME },
  { column: Column.OVERALL_TIME },
];
